# Generated by Django 4.1.1 on 2022-09-23 11:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='firstname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='lastname',
            new_name='last_name',
        ),
        migrations.AlterField(
            model_name='member',
            name='registration_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='sale',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
