# Generated by Django 4.1.1 on 2022-10-02 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_firstname_member_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='total_cost',
            new_name='total',
        ),
    ]
